### ISSUE TITLE
position

### ISSUE THREAD

**Issue by ricardo123321** [hemant-soni-vst-au4/HTML-forms#1]
this is a review of the code made by Hemant Soni of the team 97  "the Centaurus"

**Comment by ricardo123321** [comment]
the center should be footer

**Comment by ricardo123321** [comment]
the footer should be centered

**Comment by ricardo123321** [comment]
the last section of the form with  the invisible recaptcha should have the same background that the rest of the page

**Comment by ricardo123321** [comment]
add more margin-top to the footer

**Comment by LoboArkano** [comment]
Consider using nav tag

**Comment by LoboArkano** [comment]
use justify-content instead of float

**Comment by ricardo123321** [comment]
you need to add a separation between these two
![Inked_C__Users_trallero_Desktop_HTML-forms-signup_index html_LI](https://user-images.githubusercontent.com/60460371/75353006-a70a2080-5878-11ea-856d-33340c0def38.jpg)

**Comment by ricardo123321** [comment]
add separation between the text inputs and increase the width  of them

**Comment by hemantso** [comment]
corrected every issue
